### ISSUE TITLE
Issues using with mocha-webpack

### ISSUE THREAD

**Issue by alexkrautmann** [theKashey/rewiremock#6]
Hi, thanks for the hard work you have put into this project and the previous projects around the same problem-space!

I really want to use this library in my tests, but cannot get it to work at all. I receive:

```
TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/.tmp/mocha-webpack/1513799568611/webpack/bootstrap c5749b6d9b801abc09d7:637:1)
    at fn (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/.tmp/mocha-webpack/1513799568611/webpack/bootstrap c5749b6d9b801abc09d7:47:1)
    at Object../node_modules/mocha-webpack/lib/entry.js (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/.tmp/mocha-webpack/1513799568611/bundle.js:7289:73)
    at __webpack_require__ (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/.tmp/mocha-webpack/1513799568611/webpack/bootstrap c5749b6d9b801abc09d7:637:1)
    at /Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/.tmp/mocha-webpack/1513799568611/webpack/bootstrap c5749b6d9b801abc09d7:683:1
    at Object.<anonymous> (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/.tmp/mocha-webpack/1513799568611/bundle.js:687:10)
    at Module._compile (module.js:635:30)
    at Object._module2.default._extensions.(anonymous function) [as .js] (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/mocha-webpack/lib/util/registerRequireHook.js:147:12)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/mocha/lib/mocha.js:514:10)
    at /Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/mocha-webpack/lib/runner/TestRunner.js:198:25
    at Compiler.<anonymous> (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/mocha-webpack/lib/webpack/compiler/registerReadyCallback.js:26:7)
    at Compiler.applyPlugins (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:264:11)
    at Compiler.emitRecords (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:350:15)
    at /Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:1050:13)
    at /Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:958:16
    at MemoryFileSystem.writeFile (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at writeOut (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:339:28)
    at require.forEach (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:345:12)
    at /Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:3096:16
    at eachOfArrayLike (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:1055:9)
    at eachOf (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:1103:5)
    at Object.eachLimit (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/async/dist/async.js:3158:5)
    at emitFiles (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/webpack/lib/Compiler.js:315:21)
    at Immediate.<anonymous> (/Users/alexkrautmann/repos/git.cars.com/npm/react-shop-app/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Here is my webpack config:

```javascript
const path = require('path');
const fs = require('fs');
const webpack = require('webpack');
const autoprefixer = require('autoprefixer');
const postCssFlexbugsFixesPlugin = require('postcss-flexbugs-fixes');
const DotEnvPlugin = require('webpack-dotenv-extended-plugin');
const ReWireMockPlugin = require('rewiremock/webpack/plugin');

const publicPath = '/react-shop/webapp/static/';

const res = p => path.resolve(__dirname, p);

const externals = fs
    .readdirSync(res('../node_modules'))
    .filter(x => !/\.bin|react-universal-component|require-universal-module|webpack-flush-chunks/.test(x))
    .reduce((externalsAcc, mod) => {
        externalsAcc[mod] = `commonjs ${mod}`;
        return externalsAcc;
    }, {});

module.exports = {
    name: 'test',
    target: 'node',
    externals,
    devtool: 'inline-source-map',
    output: {
        publicPath,
        // use absolute paths in sourcemaps (important for debugging via IDE)
        devtoolModuleFilenameTemplate: '[absolute-resource-path]',
        devtoolFallbackModuleFilenameTemplate: '[absolute-resource-path]?[hash]',
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: 'babel-loader',
            },
            {
                test: /\.scss$/,
                use: [
                    {
                        loader: 'css-loader/locals',
                        options: {
                            modules: true,
                            localIdentName: '[name]__[local]--[hash:base64:5]',
                        },
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            // Necessary for external CSS imports to work
                            // https://github.com/facebookincubator/create-react-app/issues/2677
                            ident: 'postcss',
                            plugins: () => [
                                postCssFlexbugsFixesPlugin,
                                autoprefixer({
                                    browsers: [
                                        '>1%',
                                        'last 4 versions',
                                        'Firefox ESR',
                                        'not ie < 9', // React doesn't support IE8 anyway
                                    ],
                                    flexbox: 'no-2009',
                                }),
                            ],
                        },
                    },
                    { loader: 'sass-loader' },
                ],
            },
            {
                test: /\.(png|jpg|gif)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            // no reason to emit file on the server since we serve static from buildClient
                            emitFile: false,
                            publicPath,
                        },
                    },
                ],
            },
            {
                test: /\.svg$/,
                use: [
                    {
                        // Uses default runtimeGenerator for target=node
                        loader: 'svg-sprite-loader',
                    },
                ],
            },
        ],
    },
    resolve: {
        extensions: ['.js', '.jsx'],
        alias: { 'cars-ui': 'cars-ui/dist/scss/' },
    },
    plugins: [
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin(),
        new ReWireMockPlugin(),
        new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),
        new DotEnvPlugin({
            errorOnMissing: true,
            errorOnExtra: true,
            schema: './src/webapp/env/.env.schema',
            defaults: './src/webapp/env/.env.defaults.development',
            path: './src/webapp/env/local/.env.dev',
        }),
    ],
};
```

And I launch this all with (very long) npm script: 

```
"check-test:webapp": "cross-env NODE_ENV=test mocha-webpack --require jsdom-global/register --require babel-polyfill --webpack-config webpack/config.test.js \"src/webapp/app/components/**/*.+(js|jsx)\" \"src/webapp/app/state/**/*.+(js|jsx)\" \"src/webapp/app/pages/**/*.+(js|jsx)\" \"src/webapp/services/**/*.+(js|jsx)\" \"src/webapp/universal/**/*.+(js|jsx)\"",
```

I have tried the following uses of `.proxy`:

```javascript
describe('LazyImg', () => {
    it('binds classes with styles', () => {
        const bindClassnamesStub = sinon.stub().returns(() => {});
        const LazyImg = rewiremock.proxy(() => require('./LazyImg.component'), {
            'bind-classnames': bindClassnamesStub,
        });
        shallow(<LazyImg src="foo.com/foo" alt="Foobar" lazyHeight={109} lazyWidth={182} />);
        expect(bindClassnamesStub).to.have.been.calledWith(styles);
    });
});
```
```javascript
describe('LazyImg', () => {
    it('binds classes with styles', () => {
        const bindClassnamesStub = sinon.stub().returns(() => {});
        const LazyImg = rewiremock.proxy('./LazyImg.component', () => ({
            'bind-classnames': bindClassnamesStub,
        }));
        shallow(<LazyImg src="foo.com/foo" alt="Foobar" lazyHeight={109} lazyWidth={182} />);
        expect(bindClassnamesStub).to.have.been.calledWith(styles);
    });
});
```

```javascript
describe('LazyImg', () => {
    it('binds classes with styles', () => {
        const bindClassnamesStub = sinon.stub().returns(() => {});
        const LazyImg = rewiremock.proxy('./LazyImg.component', {
            'bind-classnames': bindClassnamesStub,
        });
        shallow(<LazyImg src="foo.com/foo" alt="Foobar" lazyHeight={109} lazyWidth={182} />);
        expect(bindClassnamesStub).to.have.been.calledWith(styles);
    });
});
```

I have also tried adding various combinations of `relative`, `nodejs`, and `webpackAlias` plugins in my `spec.helper.jsx` (which is imported in every test and exports rewiremock).

I also tried with the the low level `.enable` and `.disable` as follows:

```javascript
beforeEach(() => rewiremock.enable());
afterEach(() => rewiremock.disable());
```

I can use inject loader with `require('inject-loader!./LazyImg.component'')`, but it cannot use isolation and I would prefer not to use `require` which would force me to make considerable changes to my eslint rules.

**Comment by theKashey** [comment]
Ok, hold on a second. I have never tried mocha-webpack.

**Comment by theKashey** [comment]
Ok, so - the only thing you have to do
```js
import('rewiremock/webpack/interceptor');
```
Somewhere inside your tests. 

This file has been used by `plugin`, and it exists in webpack bundle in `karma` tests, but I did not find him inside webpack bundle for mocha-webpack. So - just import it manually.
Also - please update package version - I've also fixed some glitches you may face.

Thank you for this report. You made rewiremock better.

**Comment by Alex-Krautmann** [comment]
Thanks much for putting in the fix so quickly. 

Does this need to be a dynamic import? I am trying it without a dynamic import and still have the same issue.

**Comment by Alex-Krautmann** [comment]
@theKashey  Update as I have made some progress:

First, I needed to adjust my externals configuration so that `webpack-wipe-cache` module has `__webpack_module__` and `module.hot` available to it. Without this, it was still breaking and threw the warnings seen [in webpack-wipe-cache](https://github.com/theKashey/wipeWebpackCache/blob/master/src/index.js#L21,L36);

```javascript
    externals: [nodeExternals({
        whitelist: [/^cars-ui/, /^redux-form/, /^lodash-es/, /^rewiremock/, /^wipe-webpack-cache/],
    })],
```

This also allowed me to avoid having to import the interceptor as you had mentioned earlier. So, I now have this mostly setup, I think. 

Now I am trying to use my webpack aliases with rewiremock as described in [README.md](https://github.com/theKashey/rewiremock/blob/master/README.md#plugins)

However, I get the following error:

```
  1) LazyImg
       binds classes with styles:
     Error: Cannot find any of these configuration files: webpack.config.js, webpack.config.babel.js
      at readAliases (node_modules/rewiremock/es/plugins/common/aliases.js:55:1)
      at configure (node_modules/rewiremock/es/plugins/webpack-alias.js:7:1)
      at Object.fileNameTransformer (node_modules/rewiremock/es/plugins/webpack-alias.js:12:1)
      at node_modules/rewiremock/es/plugins.js:21:1
      at Array.reduce (<anonymous>)
      at convertName (node_modules/rewiremock/es/plugins.js:19:1)
      at mockModule (node_modules/rewiremock/es/mockModule.js:37:1)
      at node_modules/rewiremock/es/mockModule.js:145:1
      at Array.forEach (<anonymous>)
      at node_modules/rewiremock/es/mockModule.js:144:1
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.inScope (node_modules/rewiremock/es/mockModule.js:186:1)
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.proxy (node_modules/rewiremock/es/mockModule.js:143:1)
      at Context.<anonymous> (src/webapp/app/components/LazyImg/LazyImg.spec.jsx:13:36)
```

It looks like rewiremock plugins need to accept configuration so we can point webpackAlias plugin to the correct webpack config instead of depending on the default config options seen [here](https://github.com/theKashey/rewiremock/blob/master/src/plugins/common/aliases.js#L7).

I will open up an issue about this now.

**Comment by theKashey** [comment]
Look like `mocha-webpack` is a bit smarter than I expected. In my case webpack just bundled all the things I've used, even node internals. 
Thank you yet again, I'll update README with your investigations.

**Comment by Alex-Krautmann** [comment]
Of course, glad to help. Rewiremock is the dream, everything else I have tried I have had to make compromises of varying degrees.

Just a heads up though, the nodeExternals module basically makes everything in node_modules an external. The whitelist is a convenient way to force webpack to run against certain node_modules that are written with ES imports. Some common libs that need to be whitelisted are redux-form/es and lodash-es. This allows you to benefit of tree-shaking. You can easily write a function to do the same thing, but it is much more convenient and less error prone to use node-external.

Mocha-webpack suggests users to use it their docs, so other users of mocha-webpack are likely to run into the same issue.

**Comment by theKashey** [comment]
Anyway - I have to dig deeper. Have no idea how rewiremock could work in the mixed environment, as long it picks work mode only once during spinup.
Sounds like - I will have fun weekends!

**Comment by Alex-Krautmann** [comment]
So I put this aside for about a week. I just cannot get it to work. I have been debugging around the source code as much as possible, and it seems to me 

I still get:

```
     TypeError: Cannot read property 'call' of undefined
      at __webpack_require__ (.tmp/mocha-webpack/1514406431299/webpack/bootstrap 2902b08d1001f00f5cf3:637:1)
      at Array.fn (.tmp/mocha-webpack/1514406431299/webpack/bootstrap 2902b08d1001f00f5cf3:47:1)
      at baseLoader (node_modules/rewiremock/webpack/interceptor.js:5:1)
      at Object.mockLoader [as _load] (node_modules/rewiremock/es/executor.js:179:1)
      at RQ (node_modules/rewiremock/webpack/interceptor.js:13:1)
      at requireModule (node_modules/rewiremock/es/executor.js:27:1)
      at Object.require (node_modules/rewiremock/es/module.js:40:1)
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.requireActual (node_modules/rewiremock/es/mockModule.js:289:1)
      at node_modules/rewiremock/es/mockModule.js:150:1
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.inScope (node_modules/rewiremock/es/mockModule.js:186:1)
      at Function.__dirname../node_modules/rewiremock/es/mockModule.js.mockModule.proxy (node_modules/rewiremock/es/mockModule.js:143:1)
      at Context.<anonymous> (src/webapp/app/components/LazyImg/LazyImg.spec.jsx:15:36)
```

I feel like this is due to module resolution. But am quickly running out of ideas.

**Comment by theKashey** [comment]
@industral - could you copy-paste your webpack configuration?

**Comment by industral** [comment]
@theKashey 

**webpack: 3.12.0**

**webpack.conf.js**

```javascript
const path = require('path');
const webpack = require('webpack');

module.exports = {
  entry: './src/main.js',
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          'css-loader'
        ],
      },      {
        test: /\.vue$/,
        loader: 'vue-loader'
      },
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.(png|jpg|gif|svg)$/,
        loader: 'file-loader'
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url-loader',
        options: {
          limit: 10000
        }
      }
    ]
  },
  resolve: {
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': path.join(__dirname, '..', 'src'),
    },
    extensions: ['*', '.js', '.vue', '.json']
  },
  performance: {
    hints: false
  },
  plugins: [
    new webpack.NamedModulesPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new (require("rewiremock/webpack/plugin"))()
  ]
  // devtool: 'inline-source-map'
};
```

**Comment by industral** [comment]
Maybe it will help someone, mocking module could be resolved easy with  webpack functionality itself through plugin:

```javascript
  plugins: [
    new webpack.NormalModuleReplacementPlugin(
      /assets\/js\/http\.js/,
      require.resolve(__dirname + '/../src/assets/js/__mocks__/http.js')
    ),
  ]
```

https://webpack.js.org/plugins/normal-module-replacement-plugin/

**Comment by theKashey** [comment]
Static mocking is not always acceptable. 
I'll try to digg into the issue.

**Comment by ashoksudani** [comment]
@theKashey : I was getting the same error that can not call of undefined but I am not using mocha-webpack.

It did not resolved even I tried to include interceptor manually in my test 
e.g. require('rewiremock/webpack/interceptor');

When I tried to dig in and modified a code in plugin.js as below then it worked.

plugin.js : 4 
`const file = './' + relative(process.cwd(), __dirname + '/interceptor.js').replace(/\\/g, '/');`

just removed starting relative path string.

`const file = relative(process.cwd(), __dirname + '/interceptor.js').replace(/\\/g, '/');`

**Comment by theKashey** [comment]
@ashoksudani - great catch!

I've did everything you did, and everything got broken. After that I've realized that sometimes (often :)) path already contains "right" webpack module name, and adding './' _yet again_ breaks the stuff.

So `Cannot read property 'call' of undefined` means - `__webpack_require__('" + file + "')` is trying to load the file, which does not exists. Initial problem of this ticket was that plugin not get pulled into the bundle, but ends with another problem - wrong file name used to require plugin.

rewiremock@3.7.5 should work for you, @ashoksudani, and for you @alexkrautmann.

**Comment by ashoksudani** [comment]
Thank you @theKashey for quickly helping us to fix issue.

But while I am trying new version 3.7.5 I started getting another error. Error is getting popped up while trying to run a returned value from `__webpack_require__('../node_modules`... as function call.

`Uncaught TypeError: __webpack_require__(...) is not a function
    at Object.../node_modules/rewiremock/webpack/interceptor.js`


`/***/ "../node_modules/rewiremock/webpack/interceptor.js":
/*!*********************************************************************!*\
  !*** ../node_modules/rewiremock/webpack/interceptor.js ***!
  \*********************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";
/***/if(typeof __webpack_require__!=='undefined'){

__webpack_require__ = __webpack_require__('../node_modules/rewiremock/webpack/interceptor.js')(__webpack_require__, module);

}
eval("\n\nvar requires = [];......

/***/ }),

**Comment by ashoksudani** [comment]
@theKashey : I went further and just tried to check if current source code is of interceptor then dont insert interceptor inside of self content. 

Execution moved with this, and letter I have to insert interceptor manually once in my test 
`require("rewiremock/webpack/interceptor");`

Everything works ok still now.

but as soon as I put another line to require reqiremock  `var rewiremock = require('rewiremock');` I get another error of 
`VM288 context.js:248 wipeWebpackCache: you have to provide modulesNames, please add NamedModulesPlugin to your webpack configuration`

localConsole.(anonymous function) | @ | VM288 context.js:248
  | wipeCache | @ | VM315 index.js:27
  | wipeCache | @ | VM301 wipeCache.js:32
  | mockModule.flush | @ | VM337 mockModule.js:299
  | mockModule.clear | @ | VM337 mockModule.js:335
.....
baseLoader | @ | VM293 interceptor.js:7
| RQ | @ | VM293 interceptor.js:13
`

I am using karma-webpack, and my config is : 

`
{
  basePath: 'project-directory',
  files: [{ pattern: 'test/**/*-test.js', watched: true, load: false }],
  frameworks: ['mocha'],
  exclude: [],
  preprocessors: { 'test/**/*-test.js': ['webpack'] },
  reporters: ['dots', 'coverage'],
  colors: true,
  logLevel: 'WARN',
   coverageReporter:
  {
    dir: 'dist/coverage/',
    reporters: [[Object], [Object], [Object]]
  },
  port: 9876,
  webpack:
  {
    module: { rules: [Array] },
    resolve: { modules: [Array], extensions: [Array], mainFields: [Array] },
    plugins: [
      new webpack.NamedModulesPlugin(),
      new webpack.HotModuleReplacementPlugin(),
      new (require("rewiremock/webpack/plugin"))()
    ],
    performance: false,
    mode: 'development'
  },
  webpackMiddleware: { stats: 'errors-only' },
  browsers: ['Chrome'],
  browserNoActivityTimeout: 20000,
  customLaunchers:{
    ChromeHeadless: { base: 'Chrome', flags: [Array] },
    Chrome_debug: { base: 'Chrome', flags: [Array] },
    Firefox_debug: { base: 'Firefox', prefs: [Object] }
  }
}
`

**Comment by theKashey** [comment]
This error is triggered here - https://github.com/theKashey/wipeWebpackCache/blob/master/src/index.js#L35

Could you `console.log(__webpack_modules__)` somewhere, to help me figure out the name this module is presented in your build.

Could it be `../node_modules/wipe-webpack-cache/src/index.js`?

**Comment by ashoksudani** [comment]
@theKashey : Here is the list :)

0:"0"
1:"1"
2:"2"
3:"3"
4:"../sgx-scripts/node_modules/asn1.js/lib/asn1.js"
5:"../sgx-scripts/node_modules/asn1.js/lib/asn1/api.js"
6:"../sgx-scripts/node_modules/asn1.js/lib/asn1/base/buffer.js"
7:"../sgx-scripts/node_modules/asn1.js/lib/asn1/base/index.js"
8:"../sgx-scripts/node_modules/asn1.js/lib/asn1/base/node.js"
9:"../sgx-scripts/node_modules/asn1.js/lib/asn1/base/reporter.js"
10:"../sgx-scripts/node_modules/asn1.js/lib/asn1/constants/der.js"
11:"../sgx-scripts/node_modules/asn1.js/lib/asn1/constants/index.js"
12:"../sgx-scripts/node_modules/asn1.js/lib/asn1/decoders/der.js"
13:"../sgx-scripts/node_modules/asn1.js/lib/asn1/decoders/index.js"
14:"../sgx-scripts/node_modules/asn1.js/lib/asn1/decoders/pem.js"
15:"../sgx-scripts/node_modules/asn1.js/lib/asn1/encoders/der.js"
16:"../sgx-scripts/node_modules/asn1.js/lib/asn1/encoders/index.js"
17:"../sgx-scripts/node_modules/asn1.js/lib/asn1/encoders/pem.js"
18:"../sgx-scripts/node_modules/assert/assert.js"
19:"../sgx-scripts/node_modules/bn.js/lib/bn.js"
20:"../sgx-scripts/node_modules/brorand/index.js"
21:"../sgx-scripts/node_modules/browserify-aes/aes.js"
22:"../sgx-scripts/node_modules/browserify-aes/authCipher.js"
23:"../sgx-scripts/node_modules/browserify-aes/browser.js"
24:"../sgx-scripts/node_modules/browserify-aes/decrypter.js"
25:"../sgx-scripts/node_modules/browserify-aes/encrypter.js"
26:"../sgx-scripts/node_modules/browserify-aes/ghash.js"
27:"../sgx-scripts/node_modules/browserify-aes/incr32.js"
28:"../sgx-scripts/node_modules/browserify-aes/modes/cbc.js"
29:"../sgx-scripts/node_modules/browserify-aes/modes/cfb.js"
30:"../sgx-scripts/node_modules/browserify-aes/modes/cfb1.js"
31:"../sgx-scripts/node_modules/browserify-aes/modes/cfb8.js"
32:"../sgx-scripts/node_modules/browserify-aes/modes/ctr.js"
33:"../sgx-scripts/node_modules/browserify-aes/modes/ecb.js"
34:"../sgx-scripts/node_modules/browserify-aes/modes/index.js"
35:"../sgx-scripts/node_modules/browserify-aes/modes/list.json"
36:"../sgx-scripts/node_modules/browserify-aes/modes/ofb.js"
37:"../sgx-scripts/node_modules/browserify-aes/streamCipher.js"
38:"../sgx-scripts/node_modules/browserify-cipher/browser.js"
39:"../sgx-scripts/node_modules/browserify-des/index.js"
40:"../sgx-scripts/node_modules/browserify-des/modes.js"
41:"../sgx-scripts/node_modules/browserify-rsa/index.js"
42:"../sgx-scripts/node_modules/browserify-sign/algos.js"
43:"../sgx-scripts/node_modules/browserify-sign/browser/algorithms.json"
44:"../sgx-scripts/node_modules/browserify-sign/browser/curves.json"
45:"../sgx-scripts/node_modules/browserify-sign/browser/index.js"
46:"../sgx-scripts/node_modules/browserify-sign/browser/sign.js"
47:"../sgx-scripts/node_modules/browserify-sign/browser/verify.js"
48:"../sgx-scripts/node_modules/browserify-zlib/lib/binding.js"
49:"../sgx-scripts/node_modules/browserify-zlib/lib/index.js"
50:"../sgx-scripts/node_modules/buffer-xor/index.js"
51:"../sgx-scripts/node_modules/builtin-status-codes/browser.js"
52:"../sgx-scripts/node_modules/cipher-base/index.js"
53:"../sgx-scripts/node_modules/compare-module-exports/src/index.js"
54:"../sgx-scripts/node_modules/console-browserify/index.js"
55:"../sgx-scripts/node_modules/constants-browserify/constants.json"
56:"../sgx-scripts/node_modules/core-util-is/lib/util.js"
57:"../sgx-scripts/node_modules/create-ecdh/browser.js"
58:"../sgx-scripts/node_modules/create-hash/browser.js"
59:"../sgx-scripts/node_modules/create-hash/md5.js"
60:"../sgx-scripts/node_modules/create-hmac/browser.js"
61:"../sgx-scripts/node_modules/create-hmac/legacy.js"
62:"../sgx-scripts/node_modules/crypto-browserify/index.js"
63:"../sgx-scripts/node_modules/date-now/index.js"
64:"../sgx-scripts/node_modules/des.js/lib/des.js"
65:"../sgx-scripts/node_modules/des.js/lib/des/cbc.js"
66:"../sgx-scripts/node_modules/des.js/lib/des/cipher.js"
67:"../sgx-scripts/node_modules/des.js/lib/des/des.js"
68:"../sgx-scripts/node_modules/des.js/lib/des/ede.js"
69:"../sgx-scripts/node_modules/des.js/lib/des/utils.js"
70:"../sgx-scripts/node_modules/diffie-hellman/browser.js"
71:"../sgx-scripts/node_modules/diffie-hellman/lib/dh.js"
72:"../sgx-scripts/node_modules/diffie-hellman/lib/generatePrime.js"
73:"../sgx-scripts/node_modules/diffie-hellman/lib/primes.json"
74:"../sgx-scripts/node_modules/domain-browser/source/index.js"
75:"../sgx-scripts/node_modules/elliptic/lib/elliptic.js"
76:"../sgx-scripts/node_modules/elliptic/lib/elliptic/curve/base.js"
77:"../sgx-scripts/node_modules/elliptic/lib/elliptic/curve/edwards.js"
78:"../sgx-scripts/node_modules/elliptic/lib/elliptic/curve/index.js"
79:"../sgx-scripts/node_modules/elliptic/lib/elliptic/curve/mont.js"
80:"../sgx-scripts/node_modules/elliptic/lib/elliptic/curve/short.js"
81:"../sgx-scripts/node_modules/elliptic/lib/elliptic/curves.js"
82:"../sgx-scripts/node_modules/elliptic/lib/elliptic/ec/index.js"
83:"../sgx-scripts/node_modules/elliptic/lib/elliptic/ec/key.js"
84:"../sgx-scripts/node_modules/elliptic/lib/elliptic/ec/signature.js"
85:"../sgx-scripts/node_modules/elliptic/lib/elliptic/eddsa/index.js"
86:"../sgx-scripts/node_modules/elliptic/lib/elliptic/eddsa/key.js"
87:"../sgx-scripts/node_modules/elliptic/lib/elliptic/eddsa/signature.js"
88:"../sgx-scripts/node_modules/elliptic/lib/elliptic/precomputed/secp256k1.js"
89:"../sgx-scripts/node_modules/elliptic/lib/elliptic/utils.js"
90:"../sgx-scripts/node_modules/elliptic/package.json"
91:"../sgx-scripts/node_modules/events/events.js"
92:"../sgx-scripts/node_modules/evp_bytestokey/index.js"
93:"../sgx-scripts/node_modules/hash-base/index.js"
94:"../sgx-scripts/node_modules/hash.js/lib/hash.js"
95:"../sgx-scripts/node_modules/hash.js/lib/hash/common.js"
96:"../sgx-scripts/node_modules/hash.js/lib/hash/hmac.js"
97:"../sgx-scripts/node_modules/hash.js/lib/hash/ripemd.js"
98:"../sgx-scripts/node_modules/hash.js/lib/hash/sha.js"
99:"../sgx-scripts/node_modules/hash.js/lib/hash/sha/1.js"
[100 … 199]
100:"../sgx-scripts/node_modules/hash.js/lib/hash/sha/224.js"
101:"../sgx-scripts/node_modules/hash.js/lib/hash/sha/256.js"
102:"../sgx-scripts/node_modules/hash.js/lib/hash/sha/384.js"
103:"../sgx-scripts/node_modules/hash.js/lib/hash/sha/512.js"
104:"../sgx-scripts/node_modules/hash.js/lib/hash/sha/common.js"
105:"../sgx-scripts/node_modules/hash.js/lib/hash/utils.js"
106:"../sgx-scripts/node_modules/hmac-drbg/lib/hmac-drbg.js"
107:"../sgx-scripts/node_modules/https-browserify/index.js"
108:"../sgx-scripts/node_modules/ieee754/index.js"
109:"../sgx-scripts/node_modules/indexof/index.js"
110:"../sgx-scripts/node_modules/inherits/inherits_browser.js"
111:"../sgx-scripts/node_modules/isarray/index.js"
112:"../sgx-scripts/node_modules/lodash._reinterpolate/index.js"
113:"../sgx-scripts/node_modules/lodash.some/index.js"
114:"../sgx-scripts/node_modules/lodash.template/index.js"
115:"../sgx-scripts/node_modules/lodash.templatesettings/index.js"
116:"../sgx-scripts/node_modules/md5.js/index.js"
117:"../sgx-scripts/node_modules/miller-rabin/lib/mr.js"
118:"../sgx-scripts/node_modules/minimalistic-assert/index.js"
119:"../sgx-scripts/node_modules/minimalistic-crypto-utils/lib/utils.js"
120:"../sgx-scripts/node_modules/node-libs-browser/index.js"
121:"../sgx-scripts/node_modules/node-libs-browser/node_modules/base64-js/index.js"
122:"../sgx-scripts/node_modules/node-libs-browser/node_modules/buffer/index.js"
123:"../sgx-scripts/node_modules/node-libs-browser/node_modules/process/browser.js"
124:"../sgx-scripts/node_modules/os-browserify/browser.js"
125:"../sgx-scripts/node_modules/pako/lib/utils/common.js"
126:"../sgx-scripts/node_modules/pako/lib/zlib/adler32.js"
127:"../sgx-scripts/node_modules/pako/lib/zlib/constants.js"
128:"../sgx-scripts/node_modules/pako/lib/zlib/crc32.js"
129:"../sgx-scripts/node_modules/pako/lib/zlib/deflate.js"
130:"../sgx-scripts/node_modules/pako/lib/zlib/inffast.js"
131:"../sgx-scripts/node_modules/pako/lib/zlib/inflate.js"
132:"../sgx-scripts/node_modules/pako/lib/zlib/inftrees.js"
133:"../sgx-scripts/node_modules/pako/lib/zlib/messages.js"
134:"../sgx-scripts/node_modules/pako/lib/zlib/trees.js"
135:"../sgx-scripts/node_modules/pako/lib/zlib/zstream.js"
136:"../sgx-scripts/node_modules/parse-asn1/aesid.json"
137:"../sgx-scripts/node_modules/parse-asn1/asn1.js"
138:"../sgx-scripts/node_modules/parse-asn1/certificate.js"
139:"../sgx-scripts/node_modules/parse-asn1/fixProc.js"
140:"../sgx-scripts/node_modules/parse-asn1/index.js"
141:"../sgx-scripts/node_modules/path-browserify/index.js"
142:"../sgx-scripts/node_modules/path-parse/index.js"
143:"../sgx-scripts/node_modules/pbkdf2/browser.js"
144:"../sgx-scripts/node_modules/pbkdf2/lib/async.js"
145:"../sgx-scripts/node_modules/pbkdf2/lib/default-encoding.js"
146:"../sgx-scripts/node_modules/pbkdf2/lib/precondition.js"
147:"../sgx-scripts/node_modules/pbkdf2/lib/sync-browser.js"
148:"../sgx-scripts/node_modules/process-nextick-args/index.js"
149:"../sgx-scripts/node_modules/public-encrypt/browser.js"
150:"../sgx-scripts/node_modules/public-encrypt/mgf.js"
151:"../sgx-scripts/node_modules/public-encrypt/privateDecrypt.js"
152:"../sgx-scripts/node_modules/public-encrypt/publicEncrypt.js"
153:"../sgx-scripts/node_modules/public-encrypt/withPublic.js"
154:"../sgx-scripts/node_modules/public-encrypt/xor.js"
155:"../sgx-scripts/node_modules/punycode/punycode.js"
156:"../sgx-scripts/node_modules/querystring-es3/decode.js"
157:"../sgx-scripts/node_modules/querystring-es3/encode.js"
158:"../sgx-scripts/node_modules/querystring-es3/index.js"
159:"../sgx-scripts/node_modules/randombytes/browser.js"
160:"../sgx-scripts/node_modules/randomfill/browser.js"
161:"../sgx-scripts/node_modules/readable-stream/duplex-browser.js"
162:"../sgx-scripts/node_modules/readable-stream/lib/_stream_duplex.js"
163:"../sgx-scripts/node_modules/readable-stream/lib/_stream_passthrough.js"
164:"../sgx-scripts/node_modules/readable-stream/lib/_stream_readable.js"
165:"../sgx-scripts/node_modules/readable-stream/lib/_stream_transform.js"
166:"../sgx-scripts/node_modules/readable-stream/lib/_stream_writable.js"
167:"../sgx-scripts/node_modules/readable-stream/lib/internal/streams/BufferList.js"
168:"../sgx-scripts/node_modules/readable-stream/lib/internal/streams/destroy.js"
169:"../sgx-scripts/node_modules/readable-stream/lib/internal/streams/stream-browser.js"
170:"../sgx-scripts/node_modules/readable-stream/passthrough.js"
171:"../sgx-scripts/node_modules/readable-stream/readable-browser.js"
172:"../sgx-scripts/node_modules/readable-stream/transform.js"
173:"../sgx-scripts/node_modules/readable-stream/writable-browser.js"
174:"../sgx-scripts/node_modules/rewiremock/lib/_common.js"
175:"../sgx-scripts/node_modules/rewiremock/lib/asyncModules.js"
176:"../sgx-scripts/node_modules/rewiremock/lib/executor.js"
177:"../sgx-scripts/node_modules/rewiremock/lib/getModule.js"
178:"../sgx-scripts/node_modules/rewiremock/lib/globals.js"
179:"../sgx-scripts/node_modules/rewiremock/lib/index.js"
180:"../sgx-scripts/node_modules/rewiremock/lib/mock.js"
181:"../sgx-scripts/node_modules/rewiremock/lib/mockModule.js"
182:"../sgx-scripts/node_modules/rewiremock/lib/mocks.js"
183:"../sgx-scripts/node_modules/rewiremock/lib/module.js"
184:"../sgx-scripts/node_modules/rewiremock/lib/plugins.js"
185:"../sgx-scripts/node_modules/rewiremock/lib/plugins/__mock__.js"
186:"../sgx-scripts/node_modules/rewiremock/lib/plugins/_common.js"
187:"../sgx-scripts/node_modules/rewiremock/lib/plugins/childOnly.js"
188:"../sgx-scripts/node_modules/rewiremock/lib/plugins/common/aliases.js"
189:"../sgx-scripts/node_modules/rewiremock/lib/plugins/common/utils.js"
190:"../sgx-scripts/node_modules/rewiremock/lib/plugins/defaultConfig.js"
191:"../sgx-scripts/node_modules/rewiremock/lib/plugins/directChild.js"
192:"../sgx-scripts/node_modules/rewiremock/lib/plugins/disabledByDefault.js"
193:"../sgx-scripts/node_modules/rewiremock/lib/plugins/index.js"
194:"../sgx-scripts/node_modules/rewiremock/lib/plugins/mockThoughByDefault.js"
195:"../sgx-scripts/node_modules/rewiremock/lib/plugins/node-lib-browser.js"
196:"../sgx-scripts/node_modules/rewiremock/lib/plugins/nodejs.js"
197:"../sgx-scripts/node_modules/rewiremock/lib/plugins/protectNodeModules.js"
198:"../sgx-scripts/node_modules/rewiremock/lib/plugins/relative.js"
199:"../sgx-scripts/node_modules/rewiremock/lib/plugins/toBeUsed.js"
[200 … 238]
200:"../sgx-scripts/node_modules/rewiremock/lib/plugins/toMatchOrigin.js"
201:"../sgx-scripts/node_modules/rewiremock/lib/plugins/usedByDefault.js"
202:"../sgx-scripts/node_modules/rewiremock/lib/plugins/webpack-alias.js"
203:"../sgx-scripts/node_modules/rewiremock/lib/scope.js"
204:"../sgx-scripts/node_modules/rewiremock/lib/wipeCache.js"
205:"../sgx-scripts/node_modules/rewiremock/webpack/interceptor.js"
206:"../sgx-scripts/node_modules/rewiremock/webpack/module.js"
207:"../sgx-scripts/node_modules/ripemd160/index.js"
208:"../sgx-scripts/node_modules/safe-buffer/index.js"
209:"../sgx-scripts/node_modules/setimmediate/setImmediate.js"
210:"../sgx-scripts/node_modules/sha.js/hash.js"
211:"../sgx-scripts/node_modules/sha.js/index.js"
212:"../sgx-scripts/node_modules/sha.js/sha.js"
213:"../sgx-scripts/node_modules/sha.js/sha1.js"
214:"../sgx-scripts/node_modules/sha.js/sha224.js"
215:"../sgx-scripts/node_modules/sha.js/sha256.js"
216:"../sgx-scripts/node_modules/sha.js/sha384.js"
217:"../sgx-scripts/node_modules/sha.js/sha512.js"
218:"../sgx-scripts/node_modules/stream-browserify/index.js"
219:"../sgx-scripts/node_modules/stream-http/index.js"
220:"../sgx-scripts/node_modules/stream-http/lib/capability.js"
221:"../sgx-scripts/node_modules/stream-http/lib/request.js"
222:"../sgx-scripts/node_modules/stream-http/lib/response.js"
223:"../sgx-scripts/node_modules/string_decoder/lib/string_decoder.js"
224:"../sgx-scripts/node_modules/timers-browserify/main.js"
225:"../sgx-scripts/node_modules/to-arraybuffer/index.js"
226:"../sgx-scripts/node_modules/tty-browserify/index.js"
227:"../sgx-scripts/node_modules/url/url.js"
228:"../sgx-scripts/node_modules/url/util.js"
229:"../sgx-scripts/node_modules/util-deprecate/browser.js"
230:"../sgx-scripts/node_modules/util/support/isBufferBrowser.js"
231:"../sgx-scripts/node_modules/util/util.js"
232:"../sgx-scripts/node_modules/vm-browserify/index.js"
233:"../sgx-scripts/node_modules/webpack/buildin/amd-options.js"
234:"../sgx-scripts/node_modules/webpack/buildin/global.js"
235:"../sgx-scripts/node_modules/webpack/buildin/module.js"
236:"../sgx-scripts/node_modules/wipe-webpack-cache/src/index.js"
237:"../sgx-scripts/node_modules/xtend/immutable.js"
238:"./test/unit/services/sgx-ipo-service-browser-test.js"

**Comment by theKashey** [comment]
Anyway - all the node_modules are prefixed by "..", not the one I've expected

**Comment by ashoksudani** [comment]
Do you think making this module working in such a pattern of path possible? 
I can work on that then if it seems achievable.

**Comment by theKashey** [comment]
🙌 I'll port the changes. Thanks for debugging.
I have an idea why point 3 is working so strangely. `() => require` interface was created especially to "fix" any module resolution issue, and module resolution is something hardly doable with webpack runtime. It just not defined, as long usually took a place during complication.

You can't use `require` resolution with `proxy` interface, and, probably, I could fix this moment.

Just replace "Object" by "Map".
```js
const ServiceOne= rewiremock.proxy(() => require('services/service-one'), {
  ()=>require('@projectScope/project-module-one'): { ... }
  ()=>require('@projectScope/project-module-two'): {...}
});
```
But not today.

**Comment by ashoksudani** [comment]
Thanks @theKashey 
Looking forward whenever you get time to put changes.

**Comment by theKashey** [comment]
version rewiremock@3.7.6 released with changed in `interceptor` and new `wipe-webpack-cache`

**Comment by ashoksudani** [comment]
Thanks @theKashey; its working now; 

But following one condition in interceptor.js is giving an error as for empty object IF condition is true and 
failing when trying to invoke it as a function.

`if (rewiremockInterceptor)`
 
Can be more promising by:

`if (rewiremockInterceptor && typeof rewiremockInterceptor === 'function') {`

After that its working as expected.

**Comment by theKashey** [comment]
Try again :)
